### ISSUE TITLE
error: Package androidx.core.content does not exist on v2.1.0

### ISSUE THREAD

**Issue by buihoangthong123** [underscopeio/react-native-facebook-account-kit#201]
### Issue Description
Encountered a problem when debugging on Android after upgrading to v2.1.0
Compilation failed: package androidx.core.content does not exist 

### Steps to Reproduce / Code Snippets
`yarn add react-native-facebook-account-kit@latest`
`react-native link react-native-facebook-account-kit`
`cd android && ./gradlew clean` 

#### Expected Results
Build success

### Additional Information
* React Native Account Kit version: 2.1.0
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): Android
* Platform Version(s): Android API 28

**Comment by jpgarcia** [comment]
For `0.59.10` you should use `1.x.x` as described [here](https://github.com/underscopeio/react-native-facebook-account-kit/blob/master/README.MD#supported-versions---react-native--facebook-account-kit)
If you wanna use the latest version of this library you should upgrade RN
