### ISSUE TITLE
Android does not compile on RN 0.57.0

### ISSUE THREAD

**Issue by jpgarcia** [underscopeio/react-native-facebook-account-kit#155]
### Issue Description
You execute `react-native run-android` and you get the following compilation error:

```
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: android.support.design.widget.CoordinatorLayout$Behavior


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/43.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/47.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/45.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/42.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/44.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/46.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/34.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/17.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/12.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/5.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/25.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/21.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/27.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/18.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/7.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/30.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/26.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/31.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/22.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/35.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/10.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/28.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/3.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/8.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/15.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/32.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/19.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/36.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/23.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/11.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/16.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/29.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/20.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/37.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/24.jar, /Users/xxxx/Projects/community/react-native-facebook-account-kit-underscope/examples/RN057/android/app/build/intermediates/transforms/dexBuilder/debug/33.jar
```
### Steps to Reproduce / Code Snippets

- react-native init {project}
- perform installation steps
- react-native run-android

#### Expected Results

App compiles.

### Additional Information

* React Native Account Kit version:  0.11.0
* React Native version: 0.57.0
* Platform(s) (iOS, Android, or both?): Android
